# Generated by Django 2.2.4 on 2019-09-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
